### ISSUE TITLE
Error: zero-size array to reduction operation maximum

### ISSUE THREAD

**Issue by kamwal** [euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool#32]
Durring running Python code to test plots I have found the following error. This error is appearing after generating the first, trajectory plot. After this error, the code is not generating any other plots.

`C:\Users\kamwal\Anaconda3\envs\Project_test\python.exe L:/users/argo/kamwal/OWC_Python_Test_2/argodmqc_owc/owc_calibration.py
Traceback (most recent call last):
  File "L:/users/argo/kamwal/OWC_Python_Test_2/argodmqc_owc/owc_calibration.py", line 84, in <module>
    plot_diagnostics("/", FLOAT_NAME, USER_CONFIG,3)
  File "L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\ow_calibration\plot_diagnostics\plot_diagnostics.py", line 75, in plot_diagnostics
    thetas = find_10thetas(copy.deepcopy(sal), copy.deepcopy(ptmp), copy.deepcopy(pres),
  File "L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\ow_calibration\find_10thetas\find_10thetas.py", line 146, in find_10thetas
    if np.max(pres[good, depth]) > pres_levels[pres_i] > np.min(pres[good, depth]):
  File "<__array_function__ internals>", line 5, in amax
  File "C:\Users\kamwal\Anaconda3\envs\Project_test\lib\site-packages\numpy\core\fromnumeric.py", line 2667, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "C:\Users\kamwal\Anaconda3\envs\Project_test\lib\site-packages\numpy\core\fromnumeric.py", line 90, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity`

`Process finished with exit code 1`

WMO: 1901847; 3901531
Reference data: CTD_for_DMQC_2019V01
WMO boxes: wmo_boxes_ctd.mat

Cal series:
`        breaks = []
        max_breaks = 4  # 0 for linear trend, -1 for offset
        calseries = np.ones((1, no_profiles)).flatten()
        # example for splitting time series at profile 33
        # calseries = np.concatenate((np.ones((1, 33)), 2 * np.ones(1,no_profiles - 33)))
        calib_profile_no = profile_no
        use_percent_gt = 0.5
        use_theta_lt = 0
        use_theta_gt = 0
        use_pres_lt = 0
        use_pres_gt = 0`

**Comment by edsmall-bodc** [comment]
The issue is being caused by some columns being all NaN for potential temperature of the float. I need to experiment to see what matlab does in this scenario - simply ignoring those points doesn't work (see plots by @kamwal !!)

**Comment by kamwal** [comment]
![1901847_bug 10theta levels](https://user-images.githubusercontent.com/57108044/86794133-0e748000-c064-11ea-8732-c32cfa3df931.PNG)
![1901847_bug 10theta levels_2](https://user-images.githubusercontent.com/57108044/86794134-0fa5ad00-c064-11ea-881e-e5dfcef5963d.PNG)

**Comment by edsmall-bodc** [comment]
@kamwal Can you attach the testing files please?

**Comment by kamwal** [comment]
I am including data to these floats

[data.zip](https://github.com/euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool/files/4972136/data.zip)

**Comment by kamwal** [comment]
After discussion with @edsmall-bodc the fix of this issue should be done by correcting another issue with the global variables. 
I have checked these two floats and WMO:

- 1901847- still not working

- 3901531- working well

Error from running 1901847:

```
Best model found with linear fit
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
Traceback (most recent call last):
  File "L:/users/argo/kamwal/OWC_Python_Test_2/argodmqc_owc/start_with_pycharm.py", line 13, in <module>
    owc.plot.dashboard("/", FLOAT_NAME, USER_CONFIG)
  File "L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\pyowc\plot\dashboard.py", line 66, in plot_diagnostics
    thetas = find_10thetas(copy.deepcopy(sal), copy.deepcopy(ptmp), copy.deepcopy(pres),
  File "L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\pyowc\core\finders.py", line 557, in find_10thetas
    if np.max(pres[good, depth]) > pres_levels[pres_i] > np.min(pres[good, depth]):
  File "<__array_function__ internals>", line 5, in amax
  File "C:\Users\kamwal\Anaconda3\envs\Project_test\lib\site-packages\numpy\core\fromnumeric.py", line 2667, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "C:\Users\kamwal\Anaconda3\envs\Project_test\lib\site-packages\numpy\core\fromnumeric.py", line 90, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

Process finished with exit code 1
```

**Comment by edsmall-bodc** [comment]
Quite a simple fix, but revealed that the big had a slight link to https://github.com/euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool/issues/23

If we find no good data on a certain level, we should just move onto the next level.

**Comment by kamwal** [comment]
After testing the fixes provided by @edsmall-bodc,  this issue is not appearing anymore and data in calseries much better represent the results from Matlab output.

**Comment by kamwal** [comment]
The issue has been fixed and merged to the master branch
