### ISSUE TITLE
Error in displying sal_var_plot during using boundaries

### ISSUE THREAD

**Issue by kamwal** [euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool#35]
I used the output from Matlab where in set_calseres I set to select data with pressure  below 1000. I used this outut in Python and received the following error, which appeard after generating first 4 plots.

The source mapped and calibration data are in the zip file below:
[1901305.zip](https://github.com/euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool/files/4889655/1901305.zip)

`Traceback (most recent call last):
  File "L:/users/argo/kamwal/OWC_Python_Test_2/argodmqc_owc/owc_calibration.py", line 84, in <module>
    plot_diagnostics("/", FLOAT_NAME, USER_CONFIG,3)
  File "L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\ow_calibration\plot_diagnostics\plot_diagnostics.py", line 113, in plot_diagnostics
    sal_var_plot(levels, copy.deepcopy(sal), copy.deepcopy(pres),
  File "L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\ow_calibration\plot_diagnostics\sal_var_plot\sal_var_plot.py", line 128, in sal_var_plot
    pres[good] = np.nan
IndexError: index 84 is out of bounds for axis 0 with size 71`

`Process finished with exit code 1`

**Comment by kamwal** [comment]
After discussion with @edsmall-bodc we found that the error is associated with comparison of matrices in selecting data with required boundary.

**Comment by kamwal** [comment]
I run float 1901305 to try generate float_calib output in Python and I also hit the error. So the source of error can appear earlier in Python code, not necessairly in plotting part.

`Traceback (most recent call last):
  File "L:/users/argo/kamwal/OWC_Python_Test_2/argodmqc_owc/owc_calibration.py", line 81, in <module>
    calc_piecewisefit("/", FLOAT_NAME, USER_CONFIG)
  File "L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\ow_calibration\calc_piecewisefit\calc_piecewisefit.py", line 283, in calc_piecewisefit
    sta_mean, sta_rms, ndf, fit_coef, fit_breaks) = fit_cond(x, y, err,
  File "L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\ow_calibration\fit_cond\fit_cond.py", line 438, in fit_cond
    b_A[0:nbr + 2, nbr + 1] = A[0:nbr + 2]
IndexError: index 5 is out of bounds for axis 1 with size 5`

`Process finished with exit code 1`

**Comment by kamwal** [comment]
I run the test for different float for the independent check 5900178:
Code is normally generating float_calib files in Python with the boundary of pressure below 1000 m. 
However, similar as in 1901305 during the generating plots in Python, code is crashing after displying first 4 plots. 
[5900178.zip](https://github.com/euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool/files/4889980/5900178.zip)

```
Traceback (most recent call last):
  File "L:/users/argo/kamwal/OWC_Python_Test_2/argodmqc_owc/owc_calibration.py", line 84, in <module>
    plot_diagnostics("/", FLOAT_NAME, USER_CONFIG,3)
  File "L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\ow_calibration\plot_diagnostics\plot_diagnostics.py", line 113, in plot_diagnostics
    sal_var_plot(levels, copy.deepcopy(sal), copy.deepcopy(pres),
  File "L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\ow_calibration\plot_diagnostics\sal_var_plot\sal_var_plot.py", line 128, in sal_var_plot
    pres[good] = np.nan
IndexError: index 55 is out of bounds for axis 0 with size 55
```


-------------------------------------------------------------------------
In testing other boundaries "theta lt/gt" and "pres_gt" for floats e.g 5900178, there is the same type of error of 

Cal series:
```
    use_percent_gt = 0.5
        use_theta_lt = 5
        use_theta_gt = 0
        use_pres_lt = 0
        use_pres_gt = 0
```

```
 Traceback (most recent call last):
  File "L:/users/argo/kamwal/OWC_Python_Test_2/argodmqc_owc/owc_calibration.py", line 84, in <module>
    plot_diagnostics("/", FLOAT_NAME, USER_CONFIG,3)
  File "L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\ow_calibration\plot_diagnostics\plot_diagnostics.py", line 113, in plot_diagnostics
    sal_var_plot(levels, copy.deepcopy(sal), copy.deepcopy(pres),
  File "L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\ow_calibration\plot_diagnostics\sal_var_plot\sal_var_plot.py", line 83, in sal_var_plot
    pres[good] = np.nan
IndexError: index 55 is out of bounds for axis 0 with size 55 
```
-------------------------------------------------------------------------

Cal series:
    ```
  use_percent_gt = 0.5
        use_theta_lt = 0
        use_theta_gt = 5
        use_pres_lt = 0
        use_pres_gt = 0
```
```
Traceback (most recent call last):
  File "L:/users/argo/kamwal/OWC_Python_Test_2/argodmqc_owc/owc_calibration.py", line 84, in <module>
    plot_diagnostics("/", FLOAT_NAME, USER_CONFIG,3)
  File "L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\ow_calibration\plot_diagnostics\plot_diagnostics.py", line 113, in plot_diagnostics
    sal_var_plot(levels, copy.deepcopy(sal), copy.deepcopy(pres),
  File "L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\ow_calibration\plot_diagnostics\sal_var_plot\sal_var_plot.py", line 93, in sal_var_plot
    pres[good] = np.nan
IndexError: index 138 is out of bounds for axis 0 with size 55 
```
-------------------------------------------------------------------------
Cal series:

 ```
       use_percent_gt = 0.5
        use_theta_lt = 0
        use_theta_gt = 0
        use_pres_lt = 500
        use_pres_gt = 0
```

Traceback (most recent call last):
  File "L:/users/argo/kamwal/OWC_Python_Test_2/argodmqc_owc/owc_calibration.py", line 84, in <module>
    plot_diagnostics("/", FLOAT_NAME, USER_CONFIG,3)
  File "L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\ow_calibration\plot_diagnostics\plot_diagnostics.py", line 113, in plot_diagnostics
    sal_var_plot(levels, copy.deepcopy(sal), copy.deepcopy(pres),
  File "L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\ow_calibration\plot_diagnostics\sal_var_plot\sal_var_plot.py", line 118, in sal_var_plot
    pres[good] = np.nan
IndexError: index 55 is out of bounds for axis 0 with size 55

**Comment by edsmall-bodc** [comment]
I've done some investigating, and I am pretty sure that this issue will be fixed by combining the fixes in a few different pull requests.

The initial issue (borne from find_10_thetas) is a logic issue. We are accidentally removing ALL data in the ptmp/pres matrices, instead of specific data that is out of bounds. This is fixed in https://github.com/euroargodev/argodmqc_owc/pull/36 which has already been pulled in.

The secondary issue that occurs if we manage to get past the above point is a global variable issue in fit_cond. We are not reallocating a value correctly, and are therefore going out of bounds. This will be fixed when https://github.com/euroargodev/argodmqc_owc/pull/40 is merged in.

Let's revisit this issue when #40 is in.

**Comment by kamwal** [comment]
This issue has been fixed and merged to master branch

https://github.com/euroargodev/argodmqc_owc/pull/36
