### ISSUE TITLE
Problem in selecting Argo referenced data

### ISSUE THREAD

**Issue by kamwal** [euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool#8]
Durring running the OWC analysis using only Argo referenced data only, I encountered the below error:

` UPDATE_SALINITY_MAPPING: Working on profile  3
Traceback (most recent call last):
  File "L:\users\argo\kamwal\OWC_Python_SSH\owc-software-python\ow_calibration\get_region\get_region_data.py", line 172, in get_region_data
    grid_long = wrap_longitude(grid_long)
  File "L:\users\argo\kamwal\OWC_Python_SSH\owc-software-python\ow_calibration\get_region\data_functions\wrap_longitude.py", line 27, in wrap_longitude
    neg_long = np.argwhere(grid_long < 0)
TypeError: '<' not supported between instances of 'list' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "L:/users/argo/kamwal/OWC_Python_SSH/owc-software-python/owc_calibration.py", line 73, in <module>
    update_salinity_mapping("/", FLOAT_NAME, USER_CONFIG)
  File "L:\users\argo\kamwal\OWC_Python_SSH\owc-software-python\ow_calibration\update_salinity_mapping\update_salinity_mapping.py", line 330, in update_salinity_mapping
    best_hist_lat, best_hist_long, best_hist_dates] = get_region_data(wmo_numbers,
  File "L:\users\argo\kamwal\OWC_Python_SSH\owc-software-python\ow_calibration\get_region\get_region_data.py", line 198, in get_region_data
    raise Exception("NO DATA FOUND")
Exception: NO DATA FOUND

Process finished with exit code 1

`
In running the same analysis for (1) ctd+ argo and (2) CTD only, there was not such error.

FLOAT SOURCE NUMBER: 3901960
REFERENCE DATA: ARGO_for_DMQC_2020V01.mat
WMO boxes: wmo_boxes_argo.mat 
OBJECTIVE MAPPING PARAMETERS:

`       # ===============================
        #
        #    Objective Mapping Parameters
        #

        # max number of historical casts used in objective mapping
        'CONFIG_MAX_CASTS': 300,

        # 1=use PV constraint, 0=don't use PV constraint, in objective mapping
        'MAP_USE_PV': 0,

        # 1=use SAF separation criteria, 0=don't use SAF separation criteria, in objective mapping
        'MAP_USE_SAF': 0,

        # spatial decorrelation scales, in degrees
        'MAPSCALE_LONGITUDE_LARGE': 8,
        'MAPSCALE_LONGITUDE_SMALL': 2,
        'MAPSCALE_LATITUDE_LARGE': 4,
        'MAPSCALE_LATITUDE_SMALL': 1,

        # cross-isobath scales, dimensionless, see BS(2005)
        'MAPSCALE_PHI_LARGE': 0.1,
        'MAPSCALE_PHI_SMALL': 0.02,

        # temporal decorrelation scale, in years
        'MAPSCALE_AGE_LARGE': 20,
        'MAPSCALE_AGE_SMALL': 10,

        # exclude the top xxx dbar of the water column
        'MAP_P_EXCLUDE': 100,

        # only use historical data that are within +/- yyy dbar from float data
        'MAP_P_DELTA': 200`

**Comment by edsmall-bodc** [comment]
Is there a way for us to check how much argo data is in each WMO box?

**Comment by edsmall-bodc** [comment]
After a quick discussion with @kamwal we have found that the program isn't actually doing anything wrong. The matlab version also finds no data for the same profile.

However, rather than throwing an error here, we should stop the analysis at this point and move on to the next profile.

So my proposed fix is it remove the try/except clause from get_region_data and instead just check to see if we get any data that fits the analysis criteria. If we don't, we should just move on to the next profile.
